### ISSUE TITLE
API Stub

### ISSUE THREAD

**Issue by squince** [askewsoft/pantryPlus#24]
## Background
We have a data model and wireframes, now we need to connect the 2.  We need to define the basic CRUD operations on the primary objects of Shopper, Item, List, Category.

## Tasks
- [x] Set up the basics
    * express
    * eslint
    * winston
    * gitignore
    * CODEOWNERS
    * package.json scripts (start, etc)
- [x] **Shopper** REST Endpoint w/ appropriate VERBs
- [x] **List** REST Endpoint w/ appropriate VERBs
- [x] **Item** REST Endpoint w/ appropriate VERBs
- [x] **Category** REST Endpoint w/ appropriate VERBs
- [x] generate swagger docs
