### ISSUE TITLE
Apple Watch integration

### ISSUE THREAD

**Issue by squince** [askewsoft/pantryPlus#9]
**Description:**

At the moment, Pantry Plus is used by checking off items as purchased in the iPhone app. You can also use voice, including with the Apple Watch. But, unlike the Apple Reminders app, there is no way to see or interact with the Pantry Plus shopping list on an Apple Watch.

**Tasks:**

- [ ] Explore creating a companion Apple Watch app to go with the Pantry Plus mobile app
- [ ] Scope out the effort to include the following limited features
    - Select a shopping list to view
    - Enable going back to the Lists view   
    - Remove item from a shopping list
    - Purchase item on a shopping list
- [ ] Implement necessary changes
- [ ] Test in Simulator
